name = "superalink-checkout-worker"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[vars]
LOCAL_API_BASE = "https://supera.onlypast.com/storefront-api"

[[kv_namespaces]]
binding = "CHECKOUT_KV"
id = "9f9599aab1b04e32a5d609bd7cd6a56d"

# Secrets (set via `wrangler secret put`):
# - STRIPE_PK